const domain = "https://nestedspace.in";

const locationDoNotTarget = [
  "website design",
  "business website development",
  "small business website development",
  "ecommerce website development",
  "landing page development",
  "web development services",
];

const serviceDoNotTarget = [
  "website development company in Kerala",
  "website development company in Kozhikode",
  "website development company in Malappuram",
  "website development company in Wayanad",
  "website development company in Kochi",
  "website development company in Ernakulam",
  "website development company in Thrissur",
  "website development company in Bangalore",
  "website development company in Hyderabad",
];

export const seoKeywordMap = [
  {
    path: "/website-development-kerala",
    pageType: "location",
    primaryKeyword: "website development company in Kerala",
    secondaryKeywords: [
      "website development Kerala",
      "website developer Kerala",
      "web development company Kerala",
      "website design company Kerala",
      "professional website development Kerala",
    ],
    searchIntent: "Kerala-wide commercial landing page for businesses comparing website development providers.",
    geographicTarget: "Kerala",
    relatedTerms: ["responsive web design", "mobile-first website", "WhatsApp enquiries", "basic SEO setup"],
    canonicalUrl: `${domain}/website-development-kerala`,
    recommendedTitle: "Website Development Company in Kerala | Nested Space",
    recommendedMetaDescription:
      "Nested Space is a website development company in Kerala creating fast, mobile-friendly websites for businesses, shops, startups and online sellers.",
    h1: "Website Development Company in Kerala",
    doNotTarget: locationDoNotTarget,
  },
  ...[
    ["kozhikode", "Kozhikode", "Kozhikode businesses, shops, restaurants, service providers and online sellers"],
    ["malappuram", "Malappuram", "Malappuram shops, service businesses, professionals and online sellers"],
    ["wayanad", "Wayanad", "Wayanad businesses, homestays, resorts, restaurants and local shops"],
    ["kochi", "Kochi", "Kochi businesses, startups, restaurants, hospitality and online brands"],
    ["ernakulam", "Ernakulam", "businesses across Ernakulam district and surrounding areas"],
    ["thrissur", "Thrissur", "Thrissur shops, professionals, restaurants, startups and online sellers"],
    ["bangalore", "Bangalore", "Bangalore startups, SaaS teams, agencies, consultants and online brands"],
    ["hyderabad", "Hyderabad", "Hyderabad startups, technology businesses, ecommerce teams and online sellers"],
  ].map(([slug, location, audience]) => ({
    path: `/website-development-${slug}`,
    pageType: "location",
    primaryKeyword: `website development company in ${location}`,
    secondaryKeywords: [
      `website development ${location}`,
      `web development company in ${location}`,
      `business website development ${location}`,
      `website design company in ${location}`,
      `website for small businesses in ${location}`,
    ],
    searchIntent: `Commercial local-market page for ${audience}.`,
    geographicTarget: location,
    relatedTerms: ["business website", "responsive layouts", "contact forms", "WhatsApp enquiries", "deployment"],
    canonicalUrl: `${domain}/website-development-${slug}`,
    recommendedTitle: `Website Development Company in ${location} | Nested Space`,
    recommendedMetaDescription: `Nested Space provides fast, mobile-friendly website development services for ${audience}.`,
    h1: `Website Development Company in ${location}`,
    doNotTarget: locationDoNotTarget,
  })),
  {
    path: "/website-design",
    pageType: "service",
    primaryKeyword: "website design",
    secondaryKeywords: [
      "professional website design",
      "responsive website design",
      "mobile-friendly website design",
      "web design",
    ],
    searchIntent: "Design-focused users looking for professional responsive website design.",
    geographicTarget: "Non-location service intent",
    relatedTerms: ["responsive web design", "mobile-first design", "visual direction", "website layout"],
    canonicalUrl: `${domain}/website-design`,
    recommendedTitle: "Professional Website Design Services | Nested Space",
    recommendedMetaDescription:
      "Nested Space creates professional, responsive and mobile-friendly website designs for businesses, shops, startups and online sellers.",
    h1: "Professional Website Design Services",
    doNotTarget: serviceDoNotTarget,
  },
  {
    path: "/business-website-development",
    pageType: "service",
    primaryKeyword: "business website development",
    secondaryKeywords: [
      "business website development company",
      "company website development",
      "professional business website",
      "business website",
    ],
    searchIntent: "Companies and established businesses needing a professional business website.",
    geographicTarget: "Non-location service intent",
    relatedTerms: ["service sections", "company website", "contact forms", "basic SEO", "deployment"],
    canonicalUrl: `${domain}/business-website-development`,
    recommendedTitle: "Business Website Development Services | Nested Space",
    recommendedMetaDescription:
      "Nested Space builds professional business websites with mobile-friendly design, clear service sections, contact actions and basic SEO setup.",
    h1: "Business Website Development",
    doNotTarget: serviceDoNotTarget,
  },
  {
    path: "/small-business-website-development",
    pageType: "service",
    primaryKeyword: "small business website development",
    secondaryKeywords: [
      "small business website",
      "affordable business website",
      "website for small businesses",
      "small business web design",
    ],
    searchIntent: "Small businesses, local shops, freelancers, service providers and startups needing affordable websites.",
    geographicTarget: "Non-location service intent",
    relatedTerms: ["WhatsApp enquiries", "UPI-related website flows", "mobile-first design", "basic SEO setup"],
    canonicalUrl: `${domain}/small-business-website-development`,
    recommendedTitle: "Small Business Website Development | Nested Space",
    recommendedMetaDescription:
      "Nested Space creates affordable, mobile-friendly websites for small businesses, shops, service providers and online sellers.",
    h1: "Small Business Website Development",
    doNotTarget: serviceDoNotTarget,
  },
  {
    path: "/ecommerce-website-development",
    pageType: "service",
    primaryKeyword: "ecommerce website development",
    secondaryKeywords: [
      "online store website",
      "ecommerce website",
      "online shopping website development",
      "product landing page",
    ],
    searchIntent: "Businesses looking to sell or present products online.",
    geographicTarget: "Non-location service intent",
    relatedTerms: ["product sections", "online store", "payment direction", "WhatsApp orders", "mobile shoppers"],
    canonicalUrl: `${domain}/ecommerce-website-development`,
    recommendedTitle: "Ecommerce Website Development Services | Nested Space",
    recommendedMetaDescription:
      "Nested Space creates mobile-friendly ecommerce and online store website pages for sellers, shops and online brands.",
    h1: "Ecommerce Website Development",
    doNotTarget: serviceDoNotTarget,
  },
  {
    path: "/landing-page-development",
    pageType: "service",
    primaryKeyword: "landing page development",
    secondaryKeywords: [
      "landing page design",
      "business landing page",
      "campaign landing page",
      "product landing page",
    ],
    searchIntent: "Businesses needing campaign, product or service landing pages.",
    geographicTarget: "Non-location service intent",
    relatedTerms: ["single-offer page", "conversion sections", "campaign traffic", "WhatsApp CTA"],
    canonicalUrl: `${domain}/landing-page-development`,
    recommendedTitle: "Landing Page Design & Development | Nested Space",
    recommendedMetaDescription:
      "Nested Space builds focused, mobile-friendly landing pages for business offers, campaigns, products, services and online sellers.",
    h1: "Landing Page Development",
    doNotTarget: serviceDoNotTarget,
  },
  {
    path: "/web-development-services",
    pageType: "service",
    primaryKeyword: "web development services",
    secondaryKeywords: [
      "website development services",
      "professional web development",
      "custom website development",
      "frontend development",
    ],
    searchIntent: "Broader web development service searches for practical business websites and landing pages.",
    geographicTarget: "Non-location service intent",
    relatedTerms: ["frontend development", "backend development", "deployment", "hosting", "website maintenance"],
    canonicalUrl: `${domain}/web-development-services`,
    recommendedTitle: "Web Development Services | Nested Space",
    recommendedMetaDescription:
      "Nested Space provides professional web development services for mobile-friendly business websites, landing pages and online seller pages.",
    h1: "Professional Web Development Services",
    doNotTarget: serviceDoNotTarget,
  },
];

export const seoKeywordMapByPath = Object.fromEntries(seoKeywordMap.map((entry) => [entry.path, entry]));
